#!/bin/bash

fazerbackup() {
  clear
  echo "Fazendo bakcup..."
  cd /root/SuperApp
  #rm -r painelbackup > /dev/null
  #mkdir painelbackup > /dev/null
  cp prisma/database.db painelbackup
  cp .env painelbackup
  zip -r painelbackup.zip painelbackup
  mv painelbackup.zip /root
  echo
  echo "painelbackup.zip salvo em /root"
  echo
  exit 0
 }
  SuperApp
}
autobakcup() {
  clear
  read -p "Deseja ativar o Auto Backup? (s/n) " atb
  [[ $atb = @(s|S) ]] && {
    echo "Ativando...."
    backmod
    echo
    echo "Backup de 5 em 5 horas ativo!"
    exit 0
  }
  SuperApp
}
removerpainel() {
  clear
  read -p "Deseja remover o painel? (s/n) " rev
  [[ $rev = @(s|S) ]] && {
    echo "Removendo..."
    poff
    rm /bin/pon /bin/poff /bin/SuperApp /bin/backmod
    rm -r /root/SuperApp
    echo "Removido com sucesso!"
    exit 0
  }
  SuperApp
}
restaurarback() {
  clear
  [[ ! -e /root/painelbackup.zip ]] && {
    echo "Arquivo painelbackup.zip não encontrado em /root"
    sleep 4
    SuperApp
  }
  read -p "Deseja Restaurar o Backup? (s/n) " rapi
  [[ $rapi = @(s|S) ]] && {
    echo "Restaurando..."
    cd /root/SuperApp
    rm prisma/database.db
    rm .env
    cd /root
    unzip painelbackup.zip
    cd painelbackup
    mv database.db ../SuperApp/prisma
    mv .env ../SuperApp
    cd /root
    rm -r painelbackup
    pon
    echo
    echo "Backup restaurado com sucesso!"
    exit 0
  }
  [[ $rapi = @(n|N) ]] && {
    echo "Voltando para o menu"
    sleep 2
    SuperApp
  }
  SuperApp
}
#[[ ! -e /root/SuperApp/src/index.ts ]] && exit 0
SuperApp() {
  clear
  echo "Bem vindoª ao Menu SuperApp"
  echo 
  echo "1. Ligar painel"
  echo "2. Reiniciar painel"
  echo "3. Desligar painel"
  echo "4. Fazer backup"
  echo "5. Restaurar backup"
  echo "6. Ativar Auto backup"
  echo "7. Remover painel"
  echo "0. Sair"
  read -p "> " resp
  if [[ $resp = "1" ]]; then
    #statements
    clear
	pon
	echo "Painel ligado com sucesso!"
    sleep 3
    SuperApp
  elif [[ $resp = "2" ]]; then
    #statements
	clear
    echo "Reiniciando..."
    pon
	echo "Reiniciado com sucesso!"
    sleep 3
    SuperApp
  elif [[ $resp = "3" ]]; then
    #statements
	clear
	poff
	echo "Painel desligado com sucesso!"
    sleep 3
    SuperApp
  elif [[ $resp = "4" ]]; then
    #statements
    autobakcup
  elif [[ $resp = "5" ]]; then
    #statements
    restaurarback
  elif [[ $resp = "6" ]]; then
    #statements
    autobakcup
  elif [[ $resp = "7" ]]; then
    #statements
    removerpainel
  elif [[ $resp = "0" ]]; then
    #statements
    echo "Saindo..."
    exit 0
  else
    echo "Opção inválida!"
    sleep 3
    clear
    SuperApp
  fi
}
SuperApp