#!/bin/bash

fazerbackup() {
  clear
  echo "Fazendo backcup..."
  cd /root/PainelDT
  rm -r painelbackup > /dev/null
  mkdir painelbackup > /dev/null
  cp prisma/database.db painelbackup
  cp .env painelbackup
  zip -r painelbackup.zip painelbackup
  mv painelbackup.zip /root
  echo
  echo "painelbackup.zip salvo em /root"
  sleep 4
}
autobakcup() {
  clear
  read -p "Deseja ativar o Auto Backup? (s/n) " atb
  [[ $atb = @(s|S) ]] && {
    echo "Ativando...."
    backmod
    echo
    echo "Backup de 5 em 5 horas ativo!"
    sleep 4
  }
  menuop
}
removerpainel() {
  clear
  read -p "Deseja remover o painel? (s/n) " rev
  [[ $rev = @(s|S) ]] && {
    echo "Removendo..."
    poff
    rm /bin/pon /bin/poff /bin/menuop /bin/backmod
    rm -r /root/PainelDT
    echo "Removido com sucesso!"
    sleep 4
    exit 0
  }
  menuop
}
restaurarback() {
  clear
  [[ ! -e /root/painelbackup.zip ]] && {
    echo "Arquivo painelbackup.zip não encontrado em /root"
    sleep 4
    menuop
  }
  read -p "Deseja Restaurar o Backup? (s/n) " rapi
  [[ $rapi = @(s|S) ]] && {
    echo "Restaurando..."
    cd /root/PainelDT
    rm -r prisma/database.db
    rm -r .env
    cd /root
    unzip painelbackup.zip
    cd painelbackup
    mv database.db ~/PainelDT/prisma
    mv .env ~/PainelDT
    cd /root
    rm -r painelbackup
    echo
    echo "Backup restaurado com sucesso!"
    sleep 4
  }
  [[ $rapi = @(n|N) ]] && {
    echo "Voltando para o menu"
    sleep 2
    menuop
  }
  menuop
}
#[[ ! -e /root/PainelDT/src/index.ts ]] && exit 0
menuop() {
  clear
  echo "  Gestor PainelDT"
  echo 
  echo "1. Ligar"
  echo "2. Reiniciar"
  echo "3. Desligar"
  echo "4. Fazer backup"
  echo "5. Restaurar backup"
  echo "6. Ativar Auto backup"
  echo "7. Remover painel"
  echo "0. Sair"
  echo
  read -p "> " resp
  if [[ $resp = "1" ]]; then
    #statements
    clear
	pon
        screen -wipe
	sudo systemctl enable paineldt.service && sudo systemctl start paineldt.service
	echo ""
	echo "Painel ligado com sucesso!"
    sleep 2
    menuop
  elif [[ $resp = "2" ]]; then
    #statements
	clear
    echo "Reiniciando..."
    pon
    screen -wipe
	echo "Reiniciado com sucesso!"
    sleep 2
    menuop
  elif [[ $resp = "3" ]]; then
    #statements
	clear
	poff
        screen -wipe
	sudo systemctl disable --now paineldt.service && sudo systemctl stop paineldt.service && sudo systemctl daemon-reload
	echo ""
	echo "Painel desligado com sucesso!"
    sleep 2
    menuop
  elif [[ $resp = "4" ]]; then
    #statements
    fazerbackup
    echo "Backup feito com sucesso!"
    sleep 3
    menuop
  elif [[ $resp = "5" ]]; then
    #statements
    restaurarback
    echo "Backup restaurado com sucesso!"
    sleep 3s
    menuop
  elif [[ $resp = "6" ]]; then
    #statements
    autobakcup
    sleep 2
    menuop
  elif [[ $resp = "7" ]]; then
    #statements
	sudo systemctl disable --now paineldt.service && sudo systemctl stop paineldt.service && sudo systemctl daemon-reload
    removerpainel
  elif [[ $resp = "0" ]]; then
    #statements
    echo "Saindo..."
    exit 0
  else
    echo "Opção inválida!"
    sleep 3
    clear
    menuop
  fi
}
menuop